### ISSUE TITLE
Convert input json files from js-monica to "linux" Monica

### ISSUE THREAD

**Issue by ghost** [zalf-rpm/monica#21]
Hello!

I noticed that the input files (sim.json, site.json, crop.json) are slightly different, can I use the files from the js-monica model for Linux monica, or maybe I can convert them?
thank you!)

**Comment by bergm** [comment]
Hello,
js-monica is completely different and outdated. We just keep it around for educational purposes in lectures or the like and until we have a better solution.
Regarding sim, crop, site.json: What do you mean by slightly different? They contain all different parts of what MONICA needs. What do you need in order to use them or rather what would you expect?
Cheers, Michael
